config/routes.rb
# frozen_string_literal: true

Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :products do
      resources :parts do
        member do
          post :select
          post :remove
          post :set_count
        end
        collection do
          post :available
          get  :selected
        end
      end
    end
  end
end

app/models/spree/assemblies_part.rb
# frozen_string_literal: true

module Spree
  class AssembliesPart < ApplicationRecord
    belongs_to :assembly, class_name: "Spree::Product",
                          foreign_key: "assembly_id", touch: true

    belongs_to :part, class_name: "Spree::Variant", foreign_key: "part_id"

    def self.get(assembly_id, part_id)
      find_or_initialize_by(assembly_id: assembly_id, part_id: part_id)
    end
  end
end

app/models/spree/calculator/returns/assemblies_default_refund_amount.rb
# frozen_string_literal: true

module Spree
  module Calculator::Returns
    class AssembliesDefaultRefundAmount < DefaultRefundAmount
      def compute(return_item)
        percentage = return_item.inventory_unit.percentage_of_line_item
        if percentage < 1 && return_item.variant.part?
          line_item = return_item.inventory_unit.line_item
          (super * percentage * line_item.quantity).round 4, :up
        else
          super
        end
      end
    end
  end
end

app/models/spree/order_inventory_assembly.rb
# frozen_string_literal: true

module Spree
  # This class has basically the same functionality of Spree core OrderInventory
  # except that it takes account of bundle parts and properly creates and removes
  # inventory unit for each parts of a bundle
  class OrderInventoryAssembly < OrderInventory
    attr_reader :product

    def initialize(line_item)
      @order = line_item.order
      @line_item = line_item
      @product = line_item.product
    end

    def verify(shipment = nil)
      if order.completed? || shipment.present?
        line_item.quantity_by_variant.each do |part, total_parts|
          existing_parts = line_item.inventory_units.where(variant: part).count

          self.variant = part

          if existing_parts < total_parts
            if method(:determine_target_shipment).arity == 1
              quantity = total_parts - existing_parts
              shipment = determine_target_shipment(quantity) unless shipment
              add_to_shipment(shipment, quantity)
            else
              shipment = determine_target_shipment unless shipment
              add_to_shipment(shipment, total_parts - existing_parts)
            end
          elsif existing_parts > total_parts
            quantity = existing_parts - total_parts
            if shipment.present?
              remove_from_shipment(shipment, quantity)
            else
              order.shipments.each do |shipment|
                break if quantity == 0

                quantity -= remove_from_shipment(shipment, quantity)
              end
            end
          end
        end
      end
    end
  end
end

app/controllers/spree/admin/parts_controller.rb
# frozen_string_literal: true

class Spree::Admin::PartsController < Spree::Admin::BaseController
  before_action :find_product

  def index
    @parts = @product.parts
  end

  def remove
    @part = Spree::Variant.find(params[:id])
    @product.remove_part(@part)
    render 'spree/admin/parts/update_parts_table'
  end

  def set_count
    @part = Spree::Variant.find(params[:id])
    @product.set_part_count(@part, params[:count].to_i)
    render 'spree/admin/parts/update_parts_table'
  end

  def available
    if params[:q].blank?
      @available_products = []
    else
      query = "%#{params[:q]}%"
      @available_products = Spree::Product.search_can_be_part(query).distinct
    end
    respond_to do |format|
      format.html { render layout: false }
      format.js { render layout: false }
    end
  end

  def create
    @part = Spree::Variant.find(params[:part_id])
    qty = params[:part_count].to_i
    @product.add_part(@part, qty) if qty > 0
    render 'spree/admin/parts/update_parts_table'
  end

  private

  def find_product
    @product = Spree::Product.find_by(slug: params[:product_id])
  end

  def model_class
    Spree::AssembliesPart
  end
end

app/views/spree/admin/orders/_assemblies.html.erb
<% if order.line_items.assemblies.any? %>
  <fieldset class="no-border-bottom">
    <legend align="center" class="" data-hook="">
      <%= t('spree.product_bundles') %>
    </legend>
  </fieldset>

  <table class="product-bundles index" data-hook="line-items">
    <colgroup>
      <col style="width: 15%;" />
      <col style="width: 40%;" />
      <col style="width: 15%;" />
      <col style="width: 15%;" />
      <col style="width: 15%;" />
    </colgroup>

    <thead>
      <tr>
        <th colspan="2"><%= Spree::Product.human_attribute_name(:name) %></th>
        <th><%= Spree::LineItem.human_attribute_name(:price) %></th>
        <th><%= Spree::LineItem.human_attribute_name(:quantity) %></th>
        <th><%= Spree::LineItem.human_attribute_name(:total) %></th>
      </tr>
    </thead>

    <tbody>
      <% order.line_items.assemblies.each do |item| %>
        <%= content_tag :tr, class: 'line-item', id: "line-item-#{item.id}", data: { line_item_id: item.id } do %>
          <td class="line-item-image"><%= render 'spree/shared/image',
                      image: (item.variant.gallery.images.first || item.variant.product.gallery.images.first),
                      size: :mini %></td>
          <td class="line-item-name">
            <%= item.variant.product.name %><br><%= "(" + variant_options(item.variant) + ")" unless item.variant.option_values.empty? %>
            <% if item.variant.sku.present? %>
              <strong><%= Spree::Variant.human_attribute_name(:sku) %>:</strong> <%= item.variant.sku %>
            <% end %>
          </td>
          <td class="line-item-price align-center"><%= item.single_money.to_html %></td>
          <td class="line-item-qty-show align-center">
            <%= item.quantity %>
          </td>
          <td class="line-item-total align-center"><%= line_item_shipment_price(item, item.quantity) %></td>
        <% end %>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/spree/admin/orders/_stock_contents.html.erb
<%= render 'stock_item', shipment: shipment %>

<% unless shipment.shipped? %>
  <tr class="edit-shipping-method vertical-middle">
  </tr>
<% end %>

<tr class="edit-tracking vertical-middle">
</tr>

app/views/spree/admin/orders/_stock_contents_2_3.html.erb
<%= render 'stock_item', shipment: shipment %>

<% unless shipment.shipped? %>
  <tr class="edit-method hidden total">
    <td colspan="5">
      <div class="field alpha five columns">
        <%= label_tag 'selected_shipping_rate_id', t('spree.shipping_method') %>
        <%= select_tag :selected_shipping_rate_id,
              options_for_select(shipment.shipping_rates.map {|sr| ["#{sr.name} #{sr.display_price}", sr.id] }, shipment.selected_shipping_rate_id),
              {:class => 'select2 fullwidth', :data => {'shipment-number' => shipment.number } } %>
      </div>
    </td>
    <td class="actions">
      <% if can? :update, shipment %>
        <%= link_to '', '#', :class => 'save-method fa fa-ok no-text with-tip',
          :data => {'shipment-number' => shipment.number, :action => 'save'}, title: t('spree.actions.save') %>
        <%= link_to '', '#', :class => 'cancel-method fa fa-cancel no-text with-tip',
          :data => {:action => 'cancel'}, :title => t('spree.actions.cancel') %>
      <% end %>
    </td>
  </tr>
<% end %>

<tr class="show-method total">
  <% if shipment.shipping_method %>
    <td colspan="4">
      <strong><%= shipment.shipping_method.name %></strong>
    </td>
    <td class="total" align="center">
      <span><%= shipment.display_cost %></span>
    </td>
  <% else %>
    <td colspan='5'><%= t('spree.no_shipping_method_selected') %></td>
  <% end %>

  <td class="actions">
    <% if can? :update, shipment %>
      <%= link_to '', '#', :class => 'edit-method fa fa-edit no-text with-tip', :data => {:action => 'edit'}, :title => t('spree.actions.edit') %>
    <% end %>
  </td>
</tr>

<tr class="edit-tracking hidden total">
  <td colspan="5">
    <label><%= t('spree.tracking_number') %>:</label>
    <%= text_field_tag :tracking, shipment.tracking %>
  </td>
  <td class="actions">
    <% if can? :update, shipment %>
      <%= link_to '', '#', :class => 'save-tracking fa fa-ok no-text with-tip', :data => {'shipment-number' => shipment.number, :action => 'save'}, :title => t('spree.actions.save') %>
      <%= link_to '', '#', :class => 'cancel-tracking fa fa-cancel no-text with-tip', :data => {:action => 'cancel'}, :title => t('spree.actions.cancel') %>
    <% end %>
  </td>
</tr>

<tr class="show-tracking total">
  <td colspan="5" class="tracking-value">
    <% if shipment.tracking.present? %>
      <%= shipment.tracking %>
    <% else %>
      <%= t('spree.no_tracking_present') %>
    <% end %>
  </td>
  <td class="actions">
    <% if can? :update, shipment %>
      <%= link_to '', '#', :class => 'edit-tracking fa fa-edit no-text with-tip', :data => {:action => 'edit'}, :title => t('spree.actions.edit') %>
    <% end %>
  </td>
</tr>

app/views/spree/admin/orders/_stock_contents_2_4.html.erb
<%= render 'stock_item', shipment: shipment %>

<% unless shipment.shipped? %>
  <tr class="edit-method hidden total">
    <td colspan="5">
      <div class="field alpha five columns">
        <%= label_tag 'selected_shipping_rate_id', t('spree.shipping_method') %>
        <%= select_tag :selected_shipping_rate_id,
              options_for_select(shipment.shipping_rates.map {|sr| ["#{sr.name} #{sr.display_price}", sr.id] }, shipment.selected_shipping_rate_id),
              {:class => 'select2 fullwidth', :data => {'shipment-number' => shipment.number } } %>
      </div>
    </td>
    <td class="actions">
      <% if can? :update, shipment %>
        <%= button_tag '', :class => 'save-method fa fa-ok no-text with-tip',
          :data => {'shipment-number' => shipment.number, :action => 'save'}, title: t('spree.actions.save') %>
        <%= button_tag '', :class => 'cancel-method fa fa-cancel no-text with-tip',
          :data => {:action => 'cancel'}, :title => t('spree.actions.cancel') %>
      <% end %>
    </td>
  </tr>
<% end %>

<tr class="show-method total">
  <% if shipment.shipping_method %>
    <td colspan="4">
      <strong><%= shipment.shipping_method.name %></strong>
    </td>
    <td class="total" align="center">
      <span><%= shipment.display_cost %></span>
    </td>
  <% else %>
    <td colspan='5'><%= t('spree.no_shipping_method_selected') %></td>
  <% end %>

  <td class="actions">
    <% if can? :update, shipment %>
      <%= button_tag '', :class => 'edit-method fa fa-edit no-text with-tip', :data => {:action => 'edit'}, :title => t('spree.actions.edit') %>
    <% end %>
  </td>
</tr>

<tr class="edit-tracking hidden total">
  <td colspan="5">
    <label><%= t('spree.tracking_number') %>:</label>
    <%= text_field_tag :tracking, shipment.tracking %>
  </td>
  <td class="actions">
    <% if can? :update, shipment %>
      <%= button_tag '', :class => 'save-tracking fa fa-ok no-text with-tip', :data => {'shipment-number' => shipment.number, :action => 'save'}, :title => t('spree.actions.save') %>
      <%= button_tag '', :class => 'cancel-tracking fa fa-cancel no-text with-tip', :data => {:action => 'cancel'}, :title => t('spree.actions.cancel') %>
    <% end %>
  </td>
</tr>

<tr class="show-tracking total">
  <th><%= Spree::Shipment.human_attribute_name(:tracking) %></th>
  <td colspan="4" class="tracking-value">
    <% if shipment.tracking.present? %>
      <%= shipment.tracking %>
    <% else %>
      <i><%= t('spree.no_tracking_present') %></i>
    <% end %>
  </td>
  <td class="actions">
    <% if can? :update, shipment %>
      <%= button_tag '', class: 'edit-tracking fa fa-edit no-text with-tip', data: {action: 'edit'}, title: t('spree.actions.edit'), type: :button %>
    <% end %>
  </td>
</tr>

app/views/spree/admin/orders/_stock_item.html.erb
<% shipment.manifest.each do |item| %>
  <tr class="stock-item" data-item-quantity="<%= item.quantity %>" data-variant-id="<%= item.variant.id %>">
    <td class="item-image"><%= render 'spree/shared/image',
                      image: (item.variant.gallery.images.first || item.variant.product.gallery.images.first),
                      size: :mini %></td>
    <td class="item-name">
      <%= link_to item.variant.product.name, edit_admin_product_path(item.variant.product) %><br><%= "(" + variant_options(item.variant) + ")" unless item.variant.option_values.empty? %>
      <% if item.part && item.line_item %>
        <i><%= t('spree.part_of_bundle', sku: item.product.sku) %></i>
      <% elsif item.variant.sku.present? %>
        <strong><%= Spree::Variant.human_attribute_name(:sku) %>:</strong> <%= item.variant.sku %>
      <% end %>
    </td>
    <td class="item-price align-center">
      <% if item.part %>
        ---
      <% else %>
        <%= item.line_item.single_money.to_html if item.line_item %>
      <% end %>
    </td>
    <td class="item-qty-show align-center">
        <% item.states.each do |state,count| %>
          <%= count %> x <%= state.humanize.downcase %>
        <% end %>
    </td>
    <% unless shipment.shipped? %>
      <td class="item-qty-edit hidden">
        <%= number_field_tag :quantity, item.quantity, :min => 0, :class => "line_item_quantity", :size => 5 %>
      </td>
    <% end %>
    <td class="item-total align-center">
      <% if item.part %>
        ---
      <% else %>
        <%= line_item_shipment_price(item.line_item, item.quantity) if item.line_item %>
      <% end %>
    </td>
    <td class="cart-item-delete actions" data-hook="cart_item_delete">
      <% if !shipment.shipped? %>
        <% if can? :update, item %>
          <%= button_tag '', :class => 'save-item fa fa-ok no-text with-tip', :data => {'shipment-number' => shipment.number, 'variant-id' => item.variant.id, :action => 'save'}, :title => t('spree.actions.save'), :style => 'display: none' %>
          <%= link_to '', :class => 'cancel-item fa fa-cancel no-text with-tip', :data => {:action => 'cancel'}, :title => t('spree.actions.cancel'), :style => 'display: none' %>
          <%= button_tag '', :class => 'split-item fa fa-arrows-h no-text with-tip', :data => {:action => 'split', 'variant-id' => item.variant.id}, :title => t('spree.actions.split') %>
          <%= button_tag '', :class => 'delete-item fa fa-trash no-text with-tip', :data => {'shipment-number' => shipment.number, 'variant-id' => item.variant.id, :action => 'remove'}, :title => t('spree.actions.delete') %>
        <% end %>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/spree/admin/parts/_parts_table.html.erb
<table class="index">
  <thead>
  	<tr>
  	  <th><%= t('spree.sku') %></th>
      <th><%= t('spree.name') %></th>
      <th><%= t('spree.available_on') %></th>
  		<th><%= t('spree.options') %></th>
  		<th><%= t('spree.qty') %></th>
  	</tr>
  </thead>
  <tbody>
    <% parts.each do |part| %>
      <tr id="<%= dom_id(part, :sel)%>">
        <td><%= part.sku %></td>
        <td><%= part.product.name %></td>
        <td><%= part.product.available_on %></td>
        <td><%= variant_options part %></td>
        <% if can? :manage, @product%>
          <td><%= text_field_tag :count, @product.count_of(part) %></td>
        <% else %>
          <td><%= @product.count_of(part) %></td>
        <% end %>
        <% if can? :manage, @product%>
          <td class="actions">
            <%= link_to_with_icon(
              'edit',
              t('spree.actions.edit'),
              set_count_admin_product_part_url(@product, part),
              :class => "set_count_admin_product_part_link save-line-item") %>

            <%= link_to_with_icon(
            'delete',
            t('spree.actions.delete'),
            remove_admin_product_part_url(@product, part),
            class: "remove_admin_product_part_link delete-line-item") %>
          </td>
        <% end %>
      </tr>
    <% end %>
    <% if parts.empty? %>
      <tr><td colspan="5"><%= t('spree.none') %>.</td></tr>
    <% end %>
  </tbody>
</table>
<%= javascript_tag("subscribe_product_part_links();") if request.xhr? %>

app/views/spree/admin/parts/available.html.erb
<script type="text/javascript">
  function displayRow(){
    var row = document.getElementById("captionRow");
    if (row.style.display == '') row.style.display = 'none';
    else row.style.display = '';
  }
</script>

<h4><%= t('spree.available_parts') %></h4>
<table class="index">
	<thead>
		<tr>
      <th><%= t('spree.name') %></th>
      <th><%= t('spree.available_on') %></th>
  		<th><%= t('spree.options') %></th>
  		<th><%= t('spree.qty') %></th>
  		<th></th>
		</tr>
	</thead>
	<tbody>
    <% @available_products.each do |product| %>
      <tr id="<%= dom_id(product) %>">

        <td><%= product.name %></td>
        <td><%= product.available_on %></td>
        <td>
          <% if product.has_variants? %>
            <%= select_tag "part[id]",
                options_for_select(product.variants.map { |v| [variant_options(v), v.id] }) %>
          <% else %>
            <%= hidden_field_tag "part[id]", product.master.id %>
            <%= t(:no_variants) %>
          <% end %>
        </td>
        <td><%= text_field_tag "part[count]", 1 %></td>
		    <td class="actions">
		      <%= link_to(t('spree.select'),
		                  admin_product_parts_path(@product),
		                  :class => "add_product_part_link btn btn-primary") %>
		    </td>
      </tr>
    <% end %>
    <% if @available_products.empty? %>
     <tr><td colspan="3"><%= t('spree.no_match_found') %>.</td></tr>
    <% end %>
  </tbody>
</table>

<%= javascript_tag do %>
  $("a.add_product_part_link").click(function(){
    part_id_val = $('select option:selected', $(this).parent().parent()).val() ||
                  $('input:first', $(this).parent().parent()).val();
    params = { part_count :  $('input:last', $(this).parent().parent()).val(),
               part_id : part_id_val};
    return make_post_request($(this), params);
  });
<% end %>

app/views/spree/admin/parts/available.js.erb
<script type="text/javascript">
  function displayRow(){
    var row = document.getElementById("captionRow");
    if (row.style.display == '') row.style.display = 'none';
    else row.style.display = '';
  }
</script>
<h4><%= t('spree.available_parts') %></h4>
<table class="index">
	<thead>
		<tr>
        <th><%= t('spree.name') %></th>
        <th><%= t('spree.available_on') %></th>
  		<th><%= t('spree.options') %></th>
  		<th><%= t('spree.qty') %></th>
  		<th></th>
		</tr>
	</thead>
	<tbody>
    <% @available_products.each do |product| %>
      <tr id="<%= dom_id(product) %>">

        <td><%= product.name %></td>
        <td><%= product.available_on %></td>
        <td>
          <% if product.has_variants? %>
            <%= select_tag "part[id]",
                options_for_select(product.variants.map { |v| [variant_options(v), v.id] }) %>
          <% else %>
            <%= hidden_field_tag "part[id]", product.master.id %>
            <%= t('spree.no_variants') %>
          <% end %>
        </td>
        <td><%= text_field_tag "part[count]", 1 %></td>
		    <td class="actions">
		      <%= link_to(icon('add') + ' ' + t('spree.select'),
		                  admin_product_parts_path(@product),
		                  :class => "add_product_part_link") %>
		    </td>
      </tr>
    <% end %>
    <% if @available_products.empty? %>
     <tr><td colspan="3"><%= t('spree.no_match_found') %>.</td></tr>
    <% end %>
  </tbody>
</table>

<%= javascript_tag do %>
  $("a.add_product_part_link").click(function(){
    part_id_val = $('select option:selected', $(this).parent().parent()).val() ||
                  $('input:first', $(this).parent().parent()).val();
    params = { part_count :  $('input:last', $(this).parent().parent()).val(),
               part_id : part_id_val};
    return make_post_request($(this), params);
  });
<% end %>

app/views/spree/admin/parts/index.html.erb
<%# This partial was remove in solidus 1.2 but that is also when Spree.solidus_version was added %>
<%= render :partial => 'spree/admin/shared/product_sub_menu' if !Spree.respond_to?(:solidus_version) %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => "Parts"} %>
<div id="product_parts">
  <%= render :partial => "parts_table", :locals => {:parts => @parts} %>
</div>
<% if can? :available, @product%>
  <%= form_tag('#') do %>
    <label><%= t('spree.search') %>:</label>
    <input id="searchtext" size="25">
    <button id="search_parts_button" class="fa fa-search button" name="button">Search</button>
  <% end %>
<% end %>

<br/>
<div id="search_hits"></div>
<%= javascript_tag do %>
  /*!
  * Spree Product Assembly
  * https://github.com/spree/spree-product-assembly
  *
  */

  function search_for_parts(){
  $.ajax({
  data: {q: $("#searchtext").val() },
  dataType: 'html',
  success: function(request){
  jQuery('#search_hits').html(request);
  $('#search_hits').show();
  },
  type: 'POST',
  url: '<%= available_admin_product_parts_url(@product) %>'
  });
  }

  $("#searchtext").keypress(function (e) {
  if ((e.which && e.which == 13) || (e.keyCode && e.keyCode == 13)) {
  search_for_parts();
  return false;
  } else {
  return true;
  }
  });

  $("#search_parts_button").click(function(e) {
  e.preventDefault();
  search_for_parts();
  });

  function subscribe_product_part_links()
  {
  $("a.set_count_admin_product_part_link").click(function(){
  params = { count :  $("input", $(this).parent().parent()).val() };
  return make_post_request($(this), params);
  });

  $("a.remove_admin_product_part_link").click(function(){
  return make_post_request($(this), {});
  });
  }

  function make_post_request(link, post_params)
  {
  $.post(link.attr("href"), post_params, "script");
  return false;
  }

  subscribe_product_part_links();
<% end -%>

app/views/spree/admin/parts/update_parts_table.js.erb
$("#product_parts").html("<%= escape_javascript(render(:partial => "parts_table", :locals => {:parts => @product.parts})) %>");
$("#search_hits").hide();

app/views/spree/admin/products/_product_assembly_fields.html.erb
<% if false %>
  <!-- TODO temparary remove from view -->
  <div class="left six columns alpha">
    <div class="field">
      <%= f.label :can_be_part, t('spree.can_be_part')%>
      <%= f.check_box(:can_be_part) %>
    </div>
  </div>
  <div class="right six columns omega">
    <div class="field">
      <%= f.label :individual_sale, t('spree.individual_sale')%>
      <%= f.check_box(:individual_sale) %>
    </div>
  </div>
<% end %>

<% if @product.assembly? %>
  <% content_for :head do %>
    <script type="text/javascript">
      jQuery(document).ready(function(){
              $("input[id='product_on_hand']").attr('disabled',true).parent().hide();
              $("input#product_can_be_part").attr('disabled',true);
            });
    </script>
  <% end %>
<% end %>

app/views/spree/admin/shared/_product_assembly_product_tabs.html.erb
<li<%= ' class="active"' if current == "Parts" %>>
  <%= link_to_with_icon 'sitemap', t('spree.parts'), admin_product_parts_url(@product) %>
</li>

app/views/spree/checkout/_line_item_manifest.html.erb
<% ship_form.object.line_item_manifest.each do |item| %>
  <tr class="stock-item">
    <td class="item-image"><%= render 'spree/shared/image',
                      image: (item.variant.gallery.images.first || item.variant.product.gallery.images.first),
                      size: :mini %></td>
    <td class="item-name">
      <%= item.variant.name %>
      <%= render 'spree/orders/cart_description', variant: item.variant, line_item: item.line_item %>
    </td>
    <td class="item-qty">
      <% if item.line_item.product.assembly? %>
        <%= item.line_item.quantity %>
      <% else %>
        <%= item.quantity %>
      <% end %>
    </td>
    <td class="item-price"><%= item.line_item.single_money %></td>
  </tr>
<% end %>

app/views/spree/orders/_cart_description.html.erb
<% product = variant.product
  if product.assembly? %>
<ul class='assembly_parts'>
  <% line_item.parts.each do |v| %>
  <li>(<%= line_item.count_of(v) %>)  <%= link_to v.name, product_path(v.product) %>  (<%= v.sku %>)</li>
  <% end %>
</ul>
<% end %>